<?php

/**
 * BandMemberPosition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sonicdna.net (original: OpenPNE)
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
abstract class PluginBandMemberPosition extends BaseBandMemberPosition
{
}
