<?php

/**
 * PluginEventLineUpTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEventLineUpTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEventLineUpTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEventLineUp');
    }
}