<?php

/**
 * PluginTuneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginTuneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginTuneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tune');
    }
}
