<?php

/**
 * PluginTune
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sonicdna.net
 * @subpackage ##SUBPACKAGE##
 * @author     msum
 */
abstract class PluginTune extends BaseTune
{

}